### ISSUE TITLE
Endpoint for assigning Admin to a user

### ISSUE THREAD

**Issue by ChrisXJH** [follothru/follothru-backend#47]
**Description**
PUT /user/:userId/assignAdmin
Privileged: [SUPER_ADMIN]

**Comment by ChrisXJH** [comment]
This is API not working. 
PUT /user/:userId/assignAdmin.
HTTP_STATUS: 500: {"error":"failed to assign admin"}
TypeError: Cannot read property 'some' of undefined
    at findUserById.then.result (/Users/chrisxu/Documents/repos/follothru-backend/src/services/user.service.js:120:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
